### ISSUE TITLE
Add option for conditional installs

### ISSUE THREAD

**Issue by wwselleck** [d12frosted/dotbot-brew#5]
There are programs you may want to install only on your personal computer and not on your work computer, and vice versa. Add an option to conditionally run a set of installs depending on some condition. I have a (probably sloppy considering my trash shell scripting skills) [example of this in my dotfiles](https://github.com/wwselleck/dotfiles/blob/master/bin/brew.sh).

Something like
```yaml
brew:
    if: $(who | grep "some_specific_condition")
    programs:
         - work_only_program
```
