### ISSUE TITLE
Add support for services

### ISSUE THREAD

**Issue by kusold** [d12frosted/dotbot-brew#6]
```
==> Caveats
To have launchd start tor now and restart at login:
  brew services start tor
Or, if you don't want/need a background service you can just run:
  tor
```

It would be nice if you could enable services to automatically start on reboots.

**Comment by d12frosted** [comment]
Yeah, it sounds good. 💯 

FYI, PRs are welcome 😸

**Comment by d12frosted** [comment]
Services are supported via brewfiles. I think another approach would be to provide a new directive called 'bundle' that is basically brewfile verbatim (see the last example):

```yaml
- brewfile:
    - Brewfile
    - brew/Brewfile

- tap:
    - caskroom/fonts

- brew:
    - git
    - git-lfs
    - emacs --with-cocoa --with-gnutls --with-librsvg --with-imagemagick --HEAD --use-git-head

- brew: [gnupg, gnupg2]

- cask: [colorpicker, vlc]

- bundle:
    - brew "yabai", restart_service: true
```
